### ISSUE TITLE
What is the lack of configuration below error

### ISSUE THREAD

**Issue by xindinglei** [alecthomas/gozmq#105]
# github.com/alecthomas/gozmq
could not determine kind of name for C.ZMQ_HWM
could not determine kind of name for C.ZMQ_MCAST_LOOP
could not determine kind of name for C.ZMQ_RECOVERY_IVL_MSEC
could not determine kind of name for C.ZMQ_SWAP

**Comment by alecthomas** [comment]
This project is no longer maintained. See the README for details.
